name: env-vars-example
on:
  push:
    paths:
      - '.github/workflows/04-environment-variables.yml'
env:
  VENI: 'I came'
  A_FILE: 'file a'
  B_FILE: 'file b'
  
jobs:
  use-env-vars:
    runs-on: ubuntu-latest
    env:
      VIDI: 'I saw'
      CURRENT_FILE_NAME: $A_FILE
    steps:
      - uses: actions/checkout@v3

      - name: Print current path
        working-directory: ./04-environment-variables
        run: pwd
        
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: choose file name
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            CURRENT_FILE_NAME=$B_FILE
          else
            CURRENT_FILE_NAME=$A_FILE
          fi
          echo "$CURRENT_FILE_NAME"
          
      - name: Show me the vars
        run: echo "$VENI, $VIDI, $VICI"
        env:
          VICI: 'I conquered'
      
      - name: Create env var
        run: echo "foo=bar" >> $GITHUB_ENV
      
      - name: Useful default vars
        run: |
          echo "Workflow name:  $GITHUB_WORKFLOW"
          echo "Workspace:      $GITHUB_WORKSPACE"
          echo "Event:          $GITHUB_EVENT_NAME"
          echo "SHA:            $GITHUB_SHA"
          echo "Ref:            $GITHUB_REF"

      - name: Show env variables list
        run: env
